config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
mount Blazer::Engine, at: "blazer"


namespace :api, constraints: { format: "json" }, defaults: { format: "json" } do
   resources :postings , only: [:create, :index, :show , :destroy , :update]
   # resources :courses

   resources :courses 

end

  
  




  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resource :about
  resource :contact
  resources :my_tasks
  resources :tasks
  devise_for :users

  # author_courses_url #index
  # author_course_url(@course) #show
  # /author/courses
  # /author/courses/:id
  namespace :author do
    resources :courses do
      resources :lessons
    end
  end

  namespace :admin do
    resources :postings 
  end

  

  # courses_url #index
  # course_url(@course) #show
  # /courses
  # /courses/:id
  resources :courses, only: %i[index show] do
    resources :comments , module: :courses
    resources :reactions , module: :courses
    resources :content_lessons, only: %i[show ]
    resource :teacher, only: %i[show ]
    resources :completedlessons    
    resources :lessons, only: %i[index show]
    resources :enrollments, only: [:create]
 end
 resources :postings 


 
  resources :finished_courses, only: %i[show ] 
  resources :course_ratings

  # config/routes.rb
 # get '/:locale' => 'dashboard#index'

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  
  #get 'about', to: 'about#index'

  
  root 'home#index'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
end

app/models/completedlesson.rb
class Completedlesson < ApplicationRecord

    belongs_to :lesson
    belongs_to :user
    belongs_to :course



end

app/models/contact.rb
class Contact < ApplicationRecord

    # include MailForm::Delivery

    # attributes :email, :subject, :description, :format
    
    # def headers
    #     {
    #         :to => "shvalizadeh2020@gmail.com",
    #         :subject => "user created an account",
    #         :form => %("#{email} <#{description}> ")
    #     }
        
    # end
    validates :email, presence: true
    validates :subject,length: { maximum: 200 }


end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  belongs_to :user
  has_many :lessons, dependent: :destroy
  has_many :coursenrollments, dependent: :destroy
  has_many :course_ratings
  has_one_attached :image

  has_rich_text :body
  has_many :comments, as: :commentable
  has_many :reactions, as: :reactionable

  validates :title, presence: true
  validates :description,presence: true ,length: { maximum: 100 }
 # validates :publish, presence: false

  delegate :count, to: :lessons, prefix: true

  def self.chart_data
    Course.group_by_day(:created_at).count
  end

  def enrolled?(current_user)
    coursenrollments.find_by(user: current_user)
  end

  def next_lesson(lesson)
    index = lessons.find_index { |l| l.id == lesson.id }
    lessons[index + 1]
  end

  #last_lesson
  def last_lesson?(lesson)
    index = lessons.find_index { |l| l.id == lesson.id }
    index == lessons.count-1
  end

  def previous_lesson(lesson)
    index = lessons.find_index { |l| l.id == lesson.id }
    lessons[index - 1]
  end


  def progress_for(user)
    total_lessons_count = lessons.count
    completed_lessons_count = Completedlesson.where(course: self, user: user).count
    number = ((completed_lessons_count.to_f / total_lessons_count.to_f) * 100.0).to_i
    [number, 100].min

  end



  def average_rating
    course_ratings.all.average(:rating).to_i    
  end

  def average_rating_empty
  5 -   course_ratings.all.average(:rating).to_i  
  end
end

app/models/course_rating.rb
class CourseRating < ApplicationRecord
  belongs_to :course
  validates :rating, numericality: { greater_than: 0, less_than_or_equal_to: 5 }
  
  def blank_stars
    5 - rating.to_i
   end
end

app/models/coursenrollment.rb
# frozen_string_literal: true

class Coursenrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user

  #scope :completed, -> { where(completed: true) }
end

app/models/lesson.rb
# frozen_string_literal: true

class Lesson < ApplicationRecord
  belongs_to :course
  has_many  :completedlessons

  has_rich_text :body

  validates :title, presence: true
end

app/models/posting.rb
class Posting < ApplicationRecord
    
    validates :title, presence: true
    has_rich_text :body

end

app/models/reaction.rb
class Reaction < ApplicationRecord
    belongs_to :reactionable, polymorphic: true
    belongs_to :user
    enum reaction: { smile: 0, heart: 1, sad: 2 }
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    belongs_to :assignee, class_name: "User"
    has_rich_text :body

end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :courses
  has_many :coursenrollments
  has_many :tasks
  has_many :completedlessons
  has_many :finished_course


end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/my_tasks_controller.rb
class MyTasksController < ApplicationController
    before_action :set_my_task, only: [:update , :destroy , :show]

    def index
       @my_tasks= Task.where(assignee_id: current_user.id).all
      end


      def update 
        
        if @my_task.update(task_params)
           redirect_to my_tasks_url, notice: 'Task was successfully updated.'         
        else
           render :edit  
        end     
    end


    # DELETE /tasks/1
    def destroy
      @my_task.destroy
      redirect_to my_tasks_url, notice: 'Task was successfully destroyed.' 
    end


    def show
  
    end

    private

    def set_my_task
        @my_task = Task.where(assignee_id: current_user.id).find(params[:id])
      end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:my_task).permit(:title , :assignee_id , :completed)
    end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.tasks.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = current_user.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = current_user.tasks.build(task_params)
    @task.user = current_user
      if @task.save
      redirect_to tasks_url, notice: 'Task was successfully created.'  
      else
       # p @task.errors
        render :new 
      end
    
  end

  # PATCH/PUT /tasks/1
  def update
      if @task.update(task_params)
         redirect_to task_url, notice: 'Task was successfully updated.'       
      else
         render :edit 
      end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
     redirect_to tasks_url, notice: 'Task was successfully destroyed.' 
   
    end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = current_user.tasks.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title , :assignee_id)
    end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/my_tasks/index.html.erb
          <br/>

<div class="container">
  <div class="row">
        <%if @my_tasks.size == 0 %>

        <h1 class="text-center text-shadow"> There are No Tasks For You !!! </h1>
          <br/>
          <br/>
          <br/>
          <br/>
        <div class="loader  p-2">
          <div class="box">
            <div class="circle"></div>
          </div>
          <div class="box">
            <div class="circle"></div>
          </div>
        </div>
    <% else %> 
    <% @my_tasks.each do |task| %>
      <div class="col-sm m-3 hover p-2 position-relative ">  
        <div class="card shadow-lg  mb-5 bg-body rounded p-2 card-courses b-color" style="width: 18rem; height:300px">


          <div class="card-body">
            <% if task.completed? %>
            <p class="card-title">
              <%= task.title %>
              <%= link_to ' ',  my_task_path(task, {  my_task: { completed: false}  }) , class:"bi bi-check-square-fill p-2" %>                      
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-square-fill text-success" viewBox="0 0 16 16">
                <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm10.03 4.97a.75.75 0 0 1 .011 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.75.75 0 0 1 1.08-.022z"/>
                </svg>
            </p>
            <%= link_to 'Delete',  my_task_path(task, {  my_task: { completed: false} }), method: :delete, data: { confirm: 'Are you sure?' } , class:"p-2 m-2 btn text-decoration-none text-danger task-completed-style  position-absolute bottom-0 start-0" %>
            <%= link_to "Mark as completed", my_task_path(task, {  my_task: { completed: false} }), method: :patch , class:"p-2 m-2 text-decoration-none text-success task-completed-style  position-absolute bottom-0 end-0" %>
            <% else %>

            <%= task.title  %>
            <div class="m-1" >
            <%= link_to "Mark as completed", my_task_path(task, {  my_task: { completed: true} }), method: :patch , class:"p-2 m-2 text-decoration-none text-secondary task-completed-style position-absolute bottom-0 end-0" %>
            </div>
            <% end %>            
          </div>
          
          

        </div>
      </div>
    <% end %> 
    <% end %> 


  </div>
</div>

app/views/my_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @my_task.title %>
  <h1> task is Done</h1>
</p>


<%= link_to 'Back', tasks_path %>