config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
mount Blazer::Engine, at: "blazer"


namespace :api, constraints: { format: "json" }, defaults: { format: "json" } do
   resources :postings , only: [:create, :index, :show , :destroy , :update]
   # resources :courses

   resources :courses 

end

  
  




  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resource :about
  resource :contact
  resources :my_tasks
  resources :tasks
  devise_for :users

  # author_courses_url #index
  # author_course_url(@course) #show
  # /author/courses
  # /author/courses/:id
  namespace :author do
    resources :courses do
      resources :lessons
    end
  end

  namespace :admin do
    resources :postings 
  end

  

  # courses_url #index
  # course_url(@course) #show
  # /courses
  # /courses/:id
  resources :courses, only: %i[index show] do
    resources :comments , module: :courses
    resources :reactions , module: :courses
    resources :content_lessons, only: %i[show ]
    resource :teacher, only: %i[show ]
    resources :completedlessons    
    resources :lessons, only: %i[index show]
    resources :enrollments, only: [:create]
 end
 resources :postings 


 
  resources :finished_courses, only: %i[show ] 
  resources :course_ratings

  # config/routes.rb
 # get '/:locale' => 'dashboard#index'

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  
  #get 'about', to: 'about#index'

  
  root 'home#index'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/posting.rb
class Posting < ApplicationRecord
    
    validates :title, presence: true
    has_rich_text :body

end

app/controllers/admin/postings_controller.rb
module Admin
class PostingsController <  BaseController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]

  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
  end

  # GET /postings/new
  def new
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)
   
   
      if @posting.save
         redirect_to admin_postings_url, notice: 'Posting was successfully created.' 
  
      else
        render :new 
      
      end
   
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
   # respond_to do |format|    for json oder ... 
      if @posting.update(posting_params)
       redirect_to admin_postings_url, notice: 'Posting was successfully updated.' 
 
      else
       render :edit 
       
      end
   # end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
   
     redirect_to admin_postings_url, notice: 'Posting was successfully destroyed.' 
    
   
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def posting_params
      params.require(:posting).permit(:title, :description)
    end
end

end

app/controllers/api/postings_controller.rb
module Api
  # module Admin

  class PostingsController < BaseController
    before_action :set_posting, only: %i[show edit update destroy]
    respond_to :json

    def index
      # postings = Posting.order('created_at DESC')
      @postings = Posting.all
    end

    def show
      render :show
    end

    def create
      @posting = Posting.new(posting_params)
      if @posting.save
        render :show
      else
        render json: @posting.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @posting.destroy
      head :no_content
    end

    def update
      if @posting.update(posting_params)
        render :show
      else
        render json: @posting.errors, status: :unprocessable_entity
      end
    end

    private

    def set_posting
      @posting = Posting.find(params[:id])
    end

    def posting_params
      params.require(:posting).permit(:title, :body)
    end
  end

  # end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController

  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all
  end



  private

    # Only allow a list of trusted parameters through.
    def posting_params
      params.require(:posting).permit(:title, :description)
    end
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/admin/postings/_form.html.erb
<%= form_with( model: [:admin , posting]) do |form| %>
  <% if posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
        <% posting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
<div class="card p-2">
  <div class="m-3 p-2">
    <h4 class='p-2 m-2 text-shadow '>Edit Posting :</h4>

    <div class="card-body p-2 ">
      <div class="field form-group p-2">
        <%= form.label :title  , class:"form-label"%>
        <%= form.text_field :title , class:"form-control" , placeholder:"..." %>
      </div>
    </div>
  </div>




  <div class="m-3">
      <div class="card-body p-2">
        <div class="field form-group p-2 ">
          <%= form.label :description  , class:"form-label"%>
          <%= form.text_field :description , class:"form-control" , placeholder:"..." %>
        </div>
        <br/>
        <div class="actions">
          <%= form.submit class:"btn btn-success" %>
        </div>
      </div>
  </div>


  </div>
  </div>


<% end %>

app/views/admin/postings/edit.html.erb
<br/>
<br/>
<%= render 'form', posting: @posting %>
<br/>
<br/>
<%= link_to 'Show', admin_posting_url , class:"btn btn-dark p-2" %> |
<%= link_to 'Back', admin_postings_path , class:"btn btn-dark p-2"%>

app/views/admin/postings/index.html.erb
<br/>

<table class="table table-hover">
  <thead class="table-success">
<br/>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postings.each do |posting| %>
      <tr>
        <td><%= posting.title %></td>
        <td><%= posting.description %></td>
        <td><%= link_to 'Show', admin_posting_path(posting) ,class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to 'Edit', edit_admin_posting_path(posting) , class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to 'Destroy', admin_posting_path(posting), method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Posting', new_admin_posting_path , class:"btn btn-dark" %>

app/views/admin/postings/new.html.erb
<br/>
<br/>

<%= render 'form', posting: @posting %>

<%= link_to 'Back', admin_postings_path , class:"btn btn-dark p-2 m-3"  %>

app/views/admin/postings/show.html.erb
<div class="row">
<div class="col-lg-2"></div>

<div class="col-lg-8 m-5 p-2">
  <div class="container p-2">

<div class="card p-2 b-color" style="max-width: 640px;">

  <div class="card-body p-2">
    <h5 class="card-title">Post Title : </h5>
    <p class="card-text p-2"> <%= @posting.title %></p>
       <h5 class="card-title">Description: </h5>
    <p class="card-text p-2">   <%= @posting.description %></p>

    <%= link_to 'Edit', edit_admin_posting_path(@posting), class:"btn btn-dark p-2"%> |
    <%= link_to 'Back',admin_postings_path , class:"btn btn-dark p-2"%> 
  </div>

</div>



  </div>
</div>
<div class="col-lg-2"></div>
</div>