config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
mount Blazer::Engine, at: "blazer"


namespace :api, constraints: { format: "json" }, defaults: { format: "json" } do
   resources :postings , only: [:create, :index, :show , :destroy , :update]
   # resources :courses

   resources :courses 

end

  
  




  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resource :about
  resource :contact
  resources :my_tasks
  resources :tasks
  devise_for :users

  # author_courses_url #index
  # author_course_url(@course) #show
  # /author/courses
  # /author/courses/:id
  namespace :author do
    resources :courses do
      resources :lessons
    end
  end

  namespace :admin do
    resources :postings 
  end

  

  # courses_url #index
  # course_url(@course) #show
  # /courses
  # /courses/:id
  resources :courses, only: %i[index show] do
    resources :comments , module: :courses
    resources :reactions , module: :courses
    resources :content_lessons, only: %i[show ]
    resource :teacher, only: %i[show ]
    resources :completedlessons    
    resources :lessons, only: %i[index show]
    resources :enrollments, only: [:create]
 end
 resources :postings 


 
  resources :finished_courses, only: %i[show ] 
  resources :course_ratings

  # config/routes.rb
 # get '/:locale' => 'dashboard#index'

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  
  #get 'about', to: 'about#index'

  
  root 'home#index'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/courses_controller.rb
module Api
  class CoursesController < ApplicationController
    respond_to :json
    before_action :set_course, only: %i[show edit update destroy]
 


    def index
      @courses = Course.all
    end



  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :body, :description ,:published , :image)
  end


  end
end

app/controllers/author/base_controller.rb
# frozen_string_literal: true

module Author
  class BaseController < LoggedInController
    before_action :correct_user

    private

    def correct_user
      redirect_to courses_path, notice: 'Not Authorized To Edit This Course' unless current_user.author?
    end
  end
end

app/controllers/author/courses_controller.rb
# frozen_string_literal: true

module Author
  class CoursesController < BaseController
    before_action :set_course, only: %i[show edit update destroy]

  


    # GET /courses
    # GET /courses.json
    def index
      @courses = Course.all
      @chart_data = Course.chart_data
    end

    # GET /courses/1
    def show; end

    # GET /courses/new
    def new
      # @course = Course.new
      @course = current_user.courses.build
    end

    # GET /courses/1/edit
    def edit; end

    # POST /courses
    def create
      # @course = Course.new(course_params)
      @course = current_user.courses.build(course_params)
      @course.user = current_user
        if @course.save
         
         redirect_to author_courses_url, notice: 'Course was successfully created.'
        else
         render :new    
      end
    end

    # PATCH/PUT /courses/1
    def update
      respond_to do |format|
        if @course.update(course_params)
          format.html { redirect_to author_course_url, notice: 'Course was successfully updated.' }
        else
          format.html { render :edit }

        end
      end
    end

    # DELETE /courses/1
    def destroy
      @course.destroy
      respond_to do |format|
        format.html { redirect_to author_courses_url, notice: 'Course was successfully destroyed.' }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = current_user.courses.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :body, :description ,:published , :image)
    end
  end
end

app/controllers/author/lessons_controller.rb
# frozen_string_literal: true

module Author
  class LessonsController < BaseController
    before_action :set_course
    before_action :set_lesson, only: %i[show edit update destroy]

    def show; end

    # GET /Lessens/new
    def new
      @lesson = Lesson.new
    end

    # POST /lesson
    # POST /lesson.json
    def create
      @lesson = Lesson.new(lesson_params)
      @lesson.course = @course

      if @lesson.save
        redirect_to author_course_url(@course), notice: 'Lesson was successfully created.'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @lesson.update(lesson_params)
        redirect_to author_course_url(@course), notice: 'Lesson was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /lesson/1
    # DELETE /lesson/1.json
    def destroy
      @lesson.destroy
      respond_to do |format|
        format.html { redirect_to author_course_url(@course), notice: 'Lesson was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = current_user.courses.find(params[:course_id])
    end

    def set_lesson
      @lesson = @course.lessons.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :body )
    end
  end
end

app/controllers/courses/comments_controller.rb
class Courses::CommentsController < CommentsController
    before_action :set_commentable

 
    private

    def set_commentable
        @commentable = Course.find(params[:course_id])        
    end
end

app/controllers/courses/reactions_controller.rb
class Courses::ReactionsController < ReactionsController
    before_action :set_reactionable

    private

    def set_reactionable
        @reactionable = Course.find(params[:course_id])
        
    end
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  before_action :set_course, only: [:show]



  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    respond_to do |format|
      format.html
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show; end




  private


  def set_course
    @course = Course.find(params[:id])
  end



  def course_params
    params.require(:course).permit(:title, :description, :published , :image )
  end
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

app/views/author/courses/_form.html.erb
<%= form_with( model: [:author , course]) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
    <h2>
    <%= t 'general.forms.messages.errors' , count: course.errors.count%>
      </h2>
      
      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="card">
  <div class="mb-3">
    <h4 class='p-2 m-2 text-shadow '></h4>
    <div class="card-body">
      <div class="field form-group">
        <%= form.label :title , class:"form-label" %>
        <%= form.text_field :title ,class:"form-control"  , placeholder:"..."%>
      </div>
    </div>
  </div>

  <div class="mb-3">
    <div class="card-body">
      <div class="field form-group">
        <%= form.label :description , class:"form-label"%>
        <%= form.text_area :description ,  class:"form-control" ,placeholder:"..." %>
      </div>
    </div>
  </div>

  <div class="mb-3">
    <div class="card-body">
      <div class="field form-group">
        <%= form.label :body , class:"form-label"%>
        <%= form.rich_text_area :body ,  class:"form-control" ,placeholder:"..." %>
      </div>
    </div>
  </div>
 

  <div class="mb-3 ">
    <div class="card-body">
    <div class="field form-group">
      <%= form.label :image , class:"form-label"%>
      <%= form.file_field :image  , class:"form-control"%>    
    </div>
  </div>
  </div>

  

  <div class="mb-3 ">
    <div class="card-body">
      <div class="field form-group">
        <%= form.label :published %>
        <%= form.check_box :published %>
      </div>
      <br/>
      <div class="actions">
        <%= form.submit class:"btn btn-success"  %>
      </div>
    </div>
  </div>


  </div>

<% end %>

app/views/author/courses/edit.html.erb
<br/>




<br/>
<%= render 'form', course: @course %>
<br/>
<%= link_to 'Show', author_course_url , class:"btn btn-secondary" %> |
<%= link_to 'Back', author_courses_path , class:"btn btn-dark"%>

app/views/author/courses/index.html.erb
<br/>


<table class="table table-hover">

  <thead class="table-success">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
    <% if course.user == current_user %>

      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= course.published %></td>
        <td><%= link_to 'Show', author_course_path(course) ,class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to 'Edit', edit_author_course_path(course) , class: "btn btn-outline-dark btn-sm" %></td>
        <td><%= link_to 'Destroy', author_course_path(course), method: :delete, data: { confirm: 'Are you sure?' }  ,class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_author_course_path , class:"btn btn-dark"%>

<%= line_chart @chart_data %>

app/views/author/courses/new.html.erb
<br/>

<br/>
<%= render 'form', course: @course %>

<br/>
<%= link_to 'Back', author_courses_path , class:"btn btn-dark" %>

app/views/author/courses/show.html.erb
<div class="row">
<div class="col-lg-2"></div>

<div class="col-lg-8 m-5 p-2">
  <div class="container p-2">

    <div class="card  p-2 b-color shadow-lg" style="max-width: 740px;">
      <div class="row g-0 p-2">

        <div class="col-md-4 p-2">
          <% if @course.image.representable? %>
          <%= image_tag @course.image.representation(resize_to_limit: [300, 200]) , class: "img-cours-id" %>
          <% end %>
        </div>

        <div class="col-md-8 p-2">
          <div class="card-body">
            <h5 class="card-title text-capitalize"><%= @course.title %></h5>
            <p class="card-text"><%= @course.description %></p>
            <p class="card-text"><%= @course.body %></p>
            <p class="card-text"><%= @course.published %></p>
            <%#Published: <%= @course.published %>
          </div>
        </div> 

      </div>

      <div class="row g-0 p-2">
          <div class="card-body p-2">
            
            
            <table class="table table-hover">
                  <% @course.lessons.each do |lesson| %>
                     
                      <thead class="table-light">
                          <tr>
                            <td>
                                <%= link_to lesson.title, author_course_lesson_path(@course, lesson),  class: "text-decoration-none text-reset text-capitalize" %>
                            </td>
                          </tr>
                      </thead>
 
              <% end %>
            </table>



          
          </div>
      </div>    
    </div>
    <br/>
    <br/>



       <%= link_to 'Add lesson', new_author_course_lesson_path(@lesson, course_id: @course.id) , class: "btn btn-success btn-sm"%> | 
      <%= link_to 'Edit',  edit_author_course_path(@course) , class: "btn btn-dark btn-sm" %> |
      <%= link_to 'Back', author_courses_path , class: "btn btn-dark btn-sm" %>

  </div>
</div>
<div class="col-lg-2"></div>
</div>